import pandas as pd
df=pd.read_csv('swiggy.csv')
print(df)
print(df.isna().sum())
df.rename(columns={'Avg ratings':'Ratings'},inplace=True)
print(df)
print(df['Ratings'])
#df['ID']=df['ID'].astype(int)
print(df['Ratings'].isna().sum())
print(df['ID.1'].isna().sum())
print(df['Ratings'].count())
print('')
print('cleaned Swiggy Data:')
print(df)
print(df['Delivery time'])
print(df['Area'])
print(df['City'])
